# Generated by Django 2.2.6 on 2019-10-15 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'raza',
                'verbose_name_plural': 'razas',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'localidad',
                'verbose_name_plural': 'localidades',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='bio')),
                ('link', models.URLField(blank=True, null=True, verbose_name='link')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='titulo')),
                ('address', models.CharField(max_length=60, verbose_name='direccion')),
                ('description', models.TextField(verbose_name='descripción')),
                ('web', models.URLField(blank=True, null=True, verbose_name='web')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publications.Location', verbose_name='localidad')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='publications.Profile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'adiestrador',
                'verbose_name_plural': 'adiestradores',
            },
        ),
        migrations.CreateModel(
            name='Straying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(choices=[('PE', 'Perro/s'), ('GA', 'Gato/s')], max_length=2, verbose_name='animal')),
                ('genere', models.CharField(choices=[('HE', 'Hembra'), ('MA', 'Macho'), ('NO', 'No Sabe')], max_length=2, verbose_name='genero')),
                ('age', models.CharField(choices=[('CA', 'Cachorro'), ('JO', 'Joven'), ('AD', 'Adulto'), ('VI', 'Viejo')], max_length=2, verbose_name='edad')),
                ('size', models.CharField(choices=[('CH', 'Chico'), ('CM', 'Chico/Mediano'), ('ME', 'Mediano'), ('MG', 'Mediano/Grande'), ('GR', 'Grande')], max_length=2, verbose_name='tamaño')),
                ('address', models.CharField(blank=True, max_length=60, null=True, verbose_name='direccion')),
                ('tel_req', models.CharField(max_length=20, verbose_name='telefono')),
                ('tel_op', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefono2')),
                ('description', models.TextField(verbose_name='descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
                ('date_lost', models.DateField(verbose_name='fecha Extravio')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.Breed', verbose_name='raza')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publications.Location', verbose_name='localidad')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Profile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'extravio',
                'verbose_name_plural': 'extravios',
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(choices=[('PE', 'Perro/s'), ('GA', 'Gato/s')], max_length=2, verbose_name='animal')),
                ('genere', models.CharField(choices=[('HE', 'Hembra'), ('MA', 'Macho'), ('NO', 'No Sabe')], max_length=2, verbose_name='genero')),
                ('age', models.CharField(choices=[('CA', 'Cachorro'), ('JO', 'Joven'), ('AD', 'Adulto'), ('VI', 'Viejo')], max_length=2, verbose_name='edad')),
                ('size', models.CharField(choices=[('CH', 'Chico'), ('CM', 'Chico/Mediano'), ('ME', 'Mediano'), ('MG', 'Mediano/Grande'), ('GR', 'Grande')], max_length=2, verbose_name='tamaño')),
                ('address', models.CharField(blank=True, max_length=60, null=True, verbose_name='direccion')),
                ('tel_req', models.CharField(max_length=20, verbose_name='telefono')),
                ('tel_op', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefono2')),
                ('description', models.TextField(verbose_name='descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
                ('date_find', models.DateField(verbose_name='fecha Hallazgo')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.Breed', verbose_name='raza')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publications.Location', verbose_name='localidad')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Profile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'hallazgo',
                'verbose_name_plural': 'hallazgos',
            },
        ),
        migrations.CreateModel(
            name='Cross',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(choices=[('PE', 'Perro/s'), ('GA', 'Gato/s')], max_length=2, verbose_name='animal')),
                ('genere', models.CharField(choices=[('HE', 'Hembra'), ('MA', 'Macho'), ('NO', 'No Sabe')], max_length=2, verbose_name='genero')),
                ('age', models.CharField(choices=[('CA', 'Cachorro'), ('JO', 'Joven'), ('AD', 'Adulto'), ('VI', 'Viejo')], max_length=2, verbose_name='edad')),
                ('size', models.CharField(choices=[('CH', 'Chico'), ('CM', 'Chico/Mediano'), ('ME', 'Mediano'), ('MG', 'Mediano/Grande'), ('GR', 'Grande')], max_length=2, verbose_name='tamaño')),
                ('address', models.CharField(blank=True, max_length=60, null=True, verbose_name='direccion')),
                ('tel_req', models.CharField(max_length=20, verbose_name='telefono')),
                ('tel_op', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefono2')),
                ('description', models.TextField(verbose_name='descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.Breed', verbose_name='raza')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publications.Location', verbose_name='localidad')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Profile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'cruza',
                'verbose_name_plural': 'cruzas',
            },
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(choices=[('PE', 'Perro/s'), ('GA', 'Gato/s')], max_length=2, verbose_name='animal')),
                ('genere', models.CharField(choices=[('HE', 'Hembra'), ('MA', 'Macho'), ('NO', 'No Sabe')], max_length=2, verbose_name='genero')),
                ('age', models.CharField(choices=[('CA', 'Cachorro'), ('JO', 'Joven'), ('AD', 'Adulto'), ('VI', 'Viejo')], max_length=2, verbose_name='edad')),
                ('size', models.CharField(choices=[('CH', 'Chico'), ('CM', 'Chico/Mediano'), ('ME', 'Mediano'), ('MG', 'Mediano/Grande'), ('GR', 'Grande')], max_length=2, verbose_name='tamaño')),
                ('address', models.CharField(blank=True, max_length=60, null=True, verbose_name='direccion')),
                ('tel_req', models.CharField(max_length=20, verbose_name='telefono')),
                ('tel_op', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefono2')),
                ('description', models.TextField(verbose_name='descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.Breed', verbose_name='raza')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publications.Location', verbose_name='localidad')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Profile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'adopcion',
                'verbose_name_plural': 'adopciones',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='titulo')),
                ('address', models.CharField(max_length=60, verbose_name='direccion')),
                ('description', models.TextField(verbose_name='descripción')),
                ('web', models.URLField(blank=True, null=True, verbose_name='web')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publications.Location', verbose_name='localidad')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Profile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'anuncio',
                'verbose_name_plural': 'anuncios',
            },
        ),
    ]
