# Generated by Django 2.2.6 on 2019-10-15 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de edición'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de edición'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='size',
            field=models.CharField(choices=[('CH', 'Chico'), ('CM', 'Chico/Mediano'), ('ME', 'Mediano'), ('GR', 'Grande')], max_length=2, verbose_name='tamaño'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='size',
            field=models.CharField(choices=[('CH', 'Chico'), ('CM', 'Chico/Mediano'), ('ME', 'Mediano'), ('GR', 'Grande')], max_length=2, verbose_name='tamaño'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='size',
            field=models.CharField(choices=[('CH', 'Chico'), ('CM', 'Chico/Mediano'), ('ME', 'Mediano'), ('GR', 'Grande')], max_length=2, verbose_name='tamaño'),
        ),
        migrations.AlterField(
            model_name='straying',
            name='size',
            field=models.CharField(choices=[('CH', 'Chico'), ('CM', 'Chico/Mediano'), ('ME', 'Mediano'), ('GR', 'Grande')], max_length=2, verbose_name='tamaño'),
        ),
    ]
