# Generated by Django 2.2.6 on 2019-10-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20191015_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='tel_op',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telefono2'),
        ),
        migrations.AddField(
            model_name='ad',
            name='tel_req',
            field=models.CharField(default=1, max_length=20, verbose_name='telefono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='tel_op',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telefono2'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='tel_req',
            field=models.CharField(default=1, max_length=20, verbose_name='telefono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='straying',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
    ]
